### ISSUE TITLE
What is about the Gradle plugin ?

### ISSUE THREAD

**Issue by afaucogney** [GraphWalker/graphwalker.org#11]
Can we use gradle instead of maven ?

**Comment by nilols** [comment]
Usually we handle questions [here](https://groups.google.com/forum/#!forum/graphwalker-3)

We know that gradle is widely used, that's why we started with the gradle plugin, you find the source in the [project](https://github.com/GraphWalker/graphwalker-project) repository, but due to that we, ourself, doesn't use it, we never finished the plugin, and just a few days ago we talked about removing it from the project repo and put it in our labs repository, for this reason.
